name: Build and deploy to MonsterASP.NET
on: [push]
jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Restore NuGet packages
        run: nuget restore Food_Ordering_Project.sln
      - name: Build
        run: msbuild Food_Ordering_Project.sln /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:PackageLocation="./publish"
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: site81378.siteasp.net
          username: site81378
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./Food_Ordering_Project/obj/Release/Package/PackageTmp/
